# Generated by Django 4.2.1 on 2023-05-10 09:11

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Probability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                (
                    "smoke",
                    django_mysql.models.EnumField(
                        choices=[
                            ("NEVER", "NEVER"),
                            ("LIGHT", "LIGHT"),
                            ("HEAVY", "HEAVY"),
                        ]
                    ),
                ),
                ("point", models.IntegerField()),
                ("probability", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("title", models.CharField(max_length=40)),
                (
                    "questionid",
                    models.CharField(
                        max_length=40, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("username", models.CharField(max_length=40)),
                ("phone", models.CharField(max_length=40)),
                (
                    "userid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smoke",
                    django_mysql.models.EnumField(
                        choices=[
                            ("NEVER", "NEVER"),
                            ("LIGHT", "LIGHT"),
                            ("HEAVY", "HEAVY"),
                        ]
                    ),
                ),
                ("choice", models.IntegerField()),
                ("score", models.IntegerField()),
                (
                    "questionid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "pollid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "smoke",
                    django_mysql.models.EnumField(
                        choices=[
                            ("NEVER", "NEVER"),
                            ("LIGHT", "LIGHT"),
                            ("HEAVY", "HEAVY"),
                        ]
                    ),
                ),
                ("probability", models.CharField(max_length=80)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.IntegerField()),
                (
                    "pollid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.history"
                    ),
                ),
                (
                    "questionid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.CharField(max_length=200)),
                (
                    "questionid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
            ],
        ),
    ]
