# Generated by Django 4.2.1 on 2023-05-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_alter_choice_questionid"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="id",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
