# Generated by Django 4.2.1 on 2023-05-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_rename_choices_question_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="choice",
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.CharField(max_length=200)),
                (
                    "questionid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.question",
                        to_field="questionid",
                    ),
                ),
            ],
        ),
    ]
