# Generated by Django 4.2.1 on 2023-05-17 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_alter_history_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="pollid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="polls.history",
            ),
        ),
    ]
