# Generated by Django 4.2.1 on 2023-08-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_alter_detail_choice_alter_probability_probability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="choice",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="probability",
            name="probability",
            field=models.FloatField(),
        ),
    ]
